Add a library target, complete with headers that strip implementation details out.

diff --git a/.github/workflows/sanity.yml b/.github/workflows/sanity.yml
--- a/.github/workflows/sanity.yml
+++ b/.github/workflows/sanity.yml
@@ -29,7 +29,7 @@ jobs:
           ./.github/actions/install_deps.sh ${{ matrix.os }}
       - name: Build
         run: |
-          ${{ matrix.cc }} -v; (make -j sdl tester libretro ${{ matrix.extra_targets }} CONF=release CC=${{ matrix.cc }} || (echo "==== Build Failed ==="; make sdl tester libretro ${{ matrix.extra_targets }} CONF=release CC=${{ matrix.cc }}))
+          ${{ matrix.cc }} -v; (make -j all CONF=release CC=${{ matrix.cc }} || (echo "==== Build Failed ==="; make all CONF=release CC=${{ matrix.cc }}))
       - name: Sanity tests
         shell: bash
         run: |
