Update readme and the GitHub action

diff --git a/.github/workflows/sanity.yml b/.github/workflows/sanity.yml
--- a/.github/workflows/sanity.yml
+++ b/.github/workflows/sanity.yml
@@ -11,7 +11,7 @@ jobs:
         include:
         - os: macos-latest
           cc: clang
-          extra_target: cocoa
+          extra_targets: cocoa ios-ipa ios-deb
         exclude:
         - os: macos-latest
           cc: gcc
@@ -24,7 +24,7 @@ jobs:
           ./.github/actions/install_deps.sh ${{ matrix.os }}
       - name: Build
         run: |
-          ${{ matrix.cc }} -v; (make -j sdl tester libretro ${{ matrix.extra_target }} CONF=release CC=${{ matrix.cc }} || (echo "==== Build Failed ==="; make sdl tester libretro ${{ matrix.extra_target }} CONF=release CC=${{ matrix.cc }}))
+          ${{ matrix.cc }} -v; (make -j sdl tester libretro ${{ matrix.extra_targets }} CONF=release CC=${{ matrix.cc }} || (echo "==== Build Failed ==="; make sdl tester libretro ${{ matrix.extra_targets }} CONF=release CC=${{ matrix.cc }}))
       - name: Sanity tests
         shell: bash
         run: |
